# Generated by Django 4.2.16 on 2026-06-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='id',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id_paciente',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
